### ISSUE TITLE
Create Infra Mapping Wizard does not show all Clusters, when having same cluster name, on different providers.

### ISSUE THREAD

**Issue by istein1** [ManageIQ/miq_v2v_ui_plugin#248]
Setup:
2 RHV providers connected to manageIQ:
RHV1 has cluster "Default"
RHV2 has cluster "Default", and 3 more with other names.

Mapping wizard display only one cluster, "Default". 

If the cluster name, "Default" in RHV1 is changed to some other name,
the clusters section, in the Mapping wizard RHV2 clusters are displayed.

Version-Release number of selected component (if applicable):
master.20180417121918_2dd64f8 

Expected: All RHV provider should be visible, even in case same cluster name repeat for the different providers.

See also BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1571766

**Comment by vconzola** [comment]
@istein1 In the case you describe above are the two clusters named "Default" in the same datacenter? We are adding a datacenter tag to the cluster names so that two clusters with the same name in different DCs are both shown. I'm not sure having two clusters with the same name in the same DC is valid.

**Comment by istein1** [comment]
@vconzola The 2 clusters with the same name refer to clusters in 2 separate data centers, while each Datacenter belong to a different RHV providers. It is a valid situation.

**Comment by vconzola** [comment]
@istein1 OK, good. In the new UI we will display datacenter along with cluster name (PR has been merged, but not in nightly builds yet.), so that if two clusters in different datacenters have the same name, both will appear in the list of available clusters. But let's leave this issue open until you can confirm that's it's working as you expect.

**Comment by istein1** [comment]
@vconzola thanks, if you'll have info, later on, on which nightly I'll be able to consume to verify it, please tell me..

**Comment by vconzola** [comment]
@priley86 Can you confirm that this was fixed in another issue you just worked on?

**Comment by priley86** [comment]
I'm not 100% sure given this one is a little old now. I will ask QE if they can recreate it still, and if so, try to fix...

**Comment by kedark3** [comment]
@priley86 @istein1 in the latest miq nightly I am able to see something like this:
![image](https://user-images.githubusercontent.com/8180469/42521378-b0e85e36-8436-11e8-94e7-15ca6bc8597a.png)


So I believe this issue is resolved.

**Comment by priley86** [comment]
Thanks for confirming this @kedark3 (I think this issue was just dated). I will close this for now, but please reopen if you find that to be incorrect.
