### ISSUE TITLE
User views all scheduled migration plans

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/miq_v2v_ui_plugin#375]
need to verify here if we will show Scheduled Migrations "in it's own list" - 
- we may need to say given this plan, is it scheduled
- or we may need to say give me all the scheduled plans

**Comment by serenamarie125** [comment]
@blomquisg - is there an API functional requirement for this?  Or do we think "this comes for free 💸" once we have scheduled migrations

**Comment by serenamarie125** [comment]
@vconzola please add mockups for viewing scheduled migration plans 
- is there a filter for this? List View?  Column for schedule time? what would the format be?
- is there a card for scheduled migrations?  or are they lumped into "not running"

**Comment by AllenBW** [comment]
depends on #369

**Comment by AllenBW** [comment]
depends on #369

**Comment by vconzola** [comment]
@serenamarie125  I don't see a way to filter the list view for a schedule column that is present vs. not present, so I was thinking we could sort on that column by date. Also, scheduled plans are lumped into the Not Started bucket.  Mockups (WIP) [here](https://docs.google.com/presentation/d/1gMpkoVBzYb_L5orh_VFk3ZhwtLfl1S6fuI2whIdJVh8/edit?usp=sharing).

**Comment by AllenBW** [comment]
for the sake of 🖼 

<img width="960" alt="screen shot 2018-06-19 at 5 04 23 pm" src="https://user-images.githubusercontent.com/6640236/41624179-d8317414-73e2-11e8-873e-b38083dfbff9.png">

**Comment by AllenBW** [comment]
@vconzola @serenamarie125 gonna repeat back a summary of this ask, looking for yay/nay for if its close to accurate

- This work is asking for a toolbar to be added to each different state of the migration plans lists. 
- This toolbar will enable us to sort by each column of each list.
- Given we want to view only scheduled migrations, this toolbar will enable us to filter values of each of the lists

**Comment by vconzola** [comment]
@AllenBW I was thinking the toolbar would only be for the list view states - Not Started and Completed. Also, per the notes in the mockups, "Options for the sort are Name, Infrastructure Mapping, and Scheduled Date/Time. This should at least pop scheduled plans to the top of the list." However, if it's easier to sort by each column in the lists, go for it. 

Regarding viewing only scheduled migrations, I don't know how we can do that since we don't have a scheduled/not scheduled column to filter on. That's why I suggested the sort. My hope is that if we sort on the Scheduled Date/Time column plans with a schedule will appear first and those without a schedule (column contents are blank) will appear last. Is that the way ascending sort works on a field that has dates and times?

Let me know if this answers your questions and/or if you have other/better ideas.

**Comment by AllenBW** [comment]
@vconzola thanks for the quick reply! Yep that answers my questions, enough to start movin on this :heart: 🤗

**Comment by AllenBW** [comment]
@priley86 consider it done! yeah agreeeeed it would be wise not to write yasf (yet another sort function)

@vconzola need yer 👁 on this ss 👇 about the flavor of what you were thinking?  need to ask because... we'll be removing a few pf stylings from the toolbar, backgrounds, borders, box shadows...

<img width="1321" alt="screen shot 2018-06-21 at 3 25 58 pm" src="https://user-images.githubusercontent.com/6640236/41740954-a9be1c8c-7567-11e8-89fd-85a7abcedaf4.png">

**Comment by AllenBW** [comment]
@priley86 OH oh oh wait... are we gonna add pagination to this this? 

> We aren't doing pagination on the backend, so I'm assuming that it would still apply.

**Comment by priley86** [comment]
@AllenBW If we do pagination - probably want to do it across the board as a larger effort? I don't know which APIs do/don't support it so have to defer to you and @AparnaKarve . I don't think @vconzola has asked us to prioritize it yet.

**Comment by AllenBW** [comment]
@priley86 everything that has an api (should) support `limit` and `offset` so for service templates, It might look a little like this: 
```
GET http://localhost:8080/api/service_templates/?filter%5B%5D=type%3D%27ServiceTemplateTransformationPlan%27&filter%5B%5D=deleted_on%3Dnil&expand=resources&attributes=name,description,miq_requests,options,created_at&sort_by=updated_at&sort_order=desc&limit=5&offset=2
```

@vconzola present mocks don't mention pagination, is that something we want to add here?

**Comment by priley86** [comment]
@AllenBW yes, just realized we did not clarify about server vs client side pagination. We did client side pagination elsewhere, but if we decide server side is possible, then by all means. It’s probably worth re-evaluating which UIs we could server side page if that is an option.

**Comment by AparnaKarve** [comment]
> It’s probably worth re-evaluating which UIs we could server side page if that is an option.

@priley86 Agree.
Implementing Server side pagination could be an appreciable effort and would only make sense if we expect some of our lists to be really huge.

**Comment by AllenBW** [comment]
🤷‍♂️ gonna sound real cold here, but.....

Pagination wasn't mentioned in mock, not something to be done in this scope of work.

Just need quick 👁 on the ss above, to confirm its what @vconzola wants.  Reason for this ask is because it modifies a few in place PF designs (toolbar things).

**Comment by priley86** [comment]
@AllenBW - i think we decided in the sprint planning meeting to defer pagination for now. The idea being - we'd like to revisit that in the future after @vconzola rearchitects some more of the Overview UI. Let's keep it simple for now ;)
