### ISSUE TITLE
Network selection only allow one selection if you add two vCenters to v2v infra map

### ISSUE THREAD

**Issue by Yadnyawalkya** [ManageIQ/miq_v2v_ui_plugin#455]
**Description**
Let say, you have to added two vcenter to one infra map. 
You can select two clusters, two datastores but only one network.
(Please note network selection is also cluster dependent, same as datastore selection)

**Select VM network from cluster1 and then VM network from cluster2 disappear**
![select VM network from cluster1 and then after that VM network from cluster2 disappear](https://files.gitter.im/Yadnyawalkya/YRaQ/Screencast-from-2018-07-02-21-03-24.gif)

**Version-Release**
5.9.3.3.20180627151410_682cecf 

**How reproducible**
100%

**Steps to Reproduce**
1. Add two vcenter provider at source, one rhvm provider at target
2. Try to create infra-map, map two clusters (vcenter1 to vcenter2)
3. map two datastores
4. map network of first cluster and you will find network with `same name` is missing from second cluster list

What do I mean by 4th step here?
Here for cluster `V2V_Cluster (V2V)`, I mapped `vsphere6-lab \ VM Network` to `rhvm \ VM_Network` and for cluster `Cluster (V2V)` when I tried to find network, I don't see `vsphere6-cfme \ VM Network`. It is not in list.

![screenshot from 2018-06-29 13-50-58](https://user-images.githubusercontent.com/10824880/42101586-194d5aca-7be1-11e8-9aee-79d8ebb706d0.png)

**Actual results**
Only showing one network

**Expected results**
Should show two network as clusters are totally different. 

**Any workaround?** 
Workaround for this issue will be creating infra-map with single vcenter at source and single rhvm at target (that means using only one cluster at source).

**Internal reference**
https://bugzilla.redhat.com/show_bug.cgi?id=1596737

**Comment by priley86** [comment]
it seems that we are saying that a {provider}{cluster}{uid_ems} combination uniquely identifies a network instead of just the {uid_ems}. If that is the case, then we probably need to update the logic in both the mapping wizard and the infrastructure mapping list... but it would be nice confirm this before we do that.

**Comment by AparnaKarve** [comment]
> Here for cluster V2V_Cluster (V2V), I mapped vsphere6-lab \ VM Network to rhvm \ VM_Network and for cluster Cluster (V2V) when I tried to find network, I don't see vsphere6-cfme \ VM Network. It is not in list.

@Yadnyawalkya Are you expecting to see identical Networks for cluster1 and cluster2?
Is that the issue?

**Comment by Yadnyawalkya** [comment]
Updated issue with GIF which explains the issue. @priley86 @AparnaKarve

**Comment by AparnaKarve** [comment]
@priley86 @michaelkro From the above GIF, it looks like `cluster1` and `cluster2` each have a network by the name `VM Network`

When a mapping is added using `cluster1\VM Network`, it is removed from the Source Networks list of `cluster1`, which is expected.
But the issue is, it is also removed from the Source Networks list of `cluster2`

I have @Yadnyawalkya 's appliance DB with me locally. Let me know if you need it.
