### ISSUE TITLE
Clock on Dashboard and Migration Request details page not Synchronized

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/miq_v2v_ui_plugin#485]
https://bugzilla.redhat.com/show_bug.cgi?id=1600214
@mturley  I believe this is related to your PR : https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/418

**Comment by AparnaKarve** [comment]
@kedark3 I would say what you are seeing is an expected behavior since clock on Dashboard(or the Overview page) is for the `Request`, while clock on the details page is for the `Tasks`.

The `Tasks` come into picture only after the `Request` is kicked off (ordered), and approved.
So the Tasks clock is expected to lag by a couple seconds behind the Request clock.

**Comment by mturley** [comment]
@kedark3 , I agree with @AparnaKarve, I think this one is behaving as expected. So maybe not a bug, but a design improvement-- can we improve the perception that these are supposed to be the same clock?

**Comment by kedark3** [comment]
@mturley yes, we may improve the design somehow. For instance, when I look at the clock on Migration In progress card, I assume that it would show me time = max(time elapsed for vm1,time elapsed for vm2,... so on) 
Does it make sense?

**Comment by vconzola** [comment]
@kedark3 Yes, @AparnaKarve and @mturley are correct. The elapsed times for the plan and individual migrations are offset because they reflect different things. This is as designed and will likely only be noticed when a plan includes only one VM. Changing either of them to make them appear consistent would require a fairly large logic change in the UI and would not longer reflect the reality of the situation. If you think this will be a concern to customers, we can ask Avital to explain the difference in the documentation.

**Comment by vconzola** [comment]
@kedark3 How do I change the BZ to Documentation? Do I just add a tag?

**Comment by mturley** [comment]
Noticed we never swapped out `bz` for `documentation` tags here. Added the `documentation` tag, but I didn't want to remove `bz` (I'm not sure exactly what that's for)

**Comment by vconzola** [comment]
Verified that information about counters not being in sync has been added to the documentation
